### ISSUE TITLE
NPE when loading list beverages

### ISSUE THREAD

**Issue by josdem** [josdem/fruitypedia#84]
**Steps to reproduce**
- Run all test cases with this command: `./gradlew connectedAndroidTest`

**Expected Behaviour**
- All test passing

**Actual Result**
- `MainNavigationTest` failing

```java
java.lang.NullPointerException
at com.josdem.fruitypedia.BeverageFragment.displayResults(BeverageFragment.kt:97)
at com.josdem.fruitypedia.BeverageFragment.access$displayResults(BeverageFragment.kt:38)
at com.josdem.fruitypedia.BeverageFragment$onViewCreated$1.invokeSuspend(BeverageFragment.kt:72)
```

**Notes**
If we run `MainNavigationTest` test only it works as expected.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/fruitypedia/actions/runs/10029365346
